on:
  push:
    branches:
      - dont-run

  # workflow_call:
  #   secrets:
  #     GH_ACTIONS:
  #       required: true

# env:
#   NPM_REGISTRY: http://localhost:4873/
#   NPM_USER: circleci
#   NPM_PASS: circleci
#   NPM_EMAIL: circleci@amplify.js

jobs:
  e2e-prep:
    name: Runs E2E tests
    runs-on: ubuntu-latest
    outputs:
      integ-config: ${{env.INTEG_CONFIG}}
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
      #   with:
      #     # Minimal depth 2 so we can checkout the commit before possible merge commit.
      #     fetch-depth: 2
      #     path: aws-amplify
      # - name: Setup node and build the repository
      #   uses: ./aws-amplify/.github/actions/node-and-build
      # - name: Setup samples staging repository
      #   uses: ./aws-amplify/.github/actions/setup-samples-staging
      #   with:
      #     GH_ACTIONS: ${{ secrets.GH_ACTIONS }}
      # - name: Load Verdaccio with AmplifyJs
      #   uses: ./aws-amplify/.github/actions/load-verdaccio-with-amplify-js
      # - name: Where am I?
      #   run: |
      #     pwd; ls
      #   shell: bash
      # - name: Run E2E test
      #   run: |
      #     ../aws-amplify/.circleci/retry-yarn-script.sh -s 'ci:test react storage storageApp storage ${{ matrix.BROWSER }}'
      #   working-directory: amplify-js-samples-staging
      #   shell: bash

      - name: checkout AmplifyJs
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js
      - name: read integ config files
        run: echo "INTEG_CONFIG=$(cat .github/workflows/integ-config/*.yml | yq -o=json | jq -c .)" >> $GITHUB_ENV
        working-directory: ./amplify-js

  cypress:
    name: Cypress Tests
    needs: e2e-prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BROWSER: [chrome]
        integ-config: ${{ fromJson(needs.e2e-prep.outputs.integ-config) }}
    steps:
      - name: Checkout staging repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          repository: yingku/amplify-js-samples-staging
          path: aws-amplify-staging
          token: ${{ secrets.GH_ACTIONS }}
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c        
        with:
          node-version: 16
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 50
      - name: Prepare staging repo
        run: |
          pwd
          yarn
        working-directory: ./aws-amplify-staging
      - name: run the integ test
        run: |
          yarn ci:test \
          ${{ matrix.integ-config.framework }} \
          ${{ matrix.integ-config.category }} \
          ${{ matrix.integ-config.sample_name }} \
          ${{ matrix.integ-config.spec }} \
          ${{ matrix.BROWSER }} \
        working-directory: ./aws-amplify-staging