on:
  workflow_call:
    secrets:
      GH_ACTIONS:
        required: true

jobs:
  e2e-prep:
    name: Runs E2E tests
    runs-on: ubuntu-latest
    outputs:
      integ-config: ${{env.INTEG_CONFIG}}
    steps:
      - name: checkout AmplifyJs
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js
      - name: read integ config files
        run: echo "INTEG_CONFIG=$(cat .github/workflows/integ-config/*.yml | yq -o=json | jq -c .)" >> $GITHUB_ENV
        working-directory: ./amplify-js

  e2e-test:
    name: Cypress Tests
    needs: e2e-prep
    strategy:
      matrix:
        integ-config: ${{ fromJson(needs.e2e-prep.outputs.integ-config) }}
    uses: ./.github/workflows/callable-unit-tests.yml
    with:
      test_name: ${{ matrix.integ-config.test_name }}
      framework: ${{ matrix.integ-config.framework }}
      category: ${{ matrix.integ-config.category }}
      sample_name: ${{ matrix.integ-config.sample_name }}
      spec: ${{ matrix.integ-config.spec }}
      browser: ${{ matrix.integ-config.browser }}