on:
  workflow_call:
    secrets:
      GH_ACTIONS:
        required: true
env:
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js

jobs:
  e2e-tests:
    name: Runs E2E tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BROWSER: [chrome, firefox]
    steps:
      - name: Setup node and build the repository
        uses: ./aws-amplify/.github/actions/node-and-build
      - name: Checkout staging repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          repository: yingku/amplify-js-samples-staging
          path: aws-amplify-staging
          token: ${{ secrets.GH_ACTIONS }}
          fetch-depth: 2
      - name: Prepare staging repo
        run: |
          yarn
        working-directory: ./aws-amplify-staging
      - name: Start verdaccio
        run: |
          npx verdaccio@5.25.0 &
          sleep 15 # TODO waits until verdaccio is up and running
      - name: Publish to verdaccio
        run: |
