name: Push Validation 
on: [push]
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          fetch-depth: 2
          path: aws-amplify
      - name: Setup node and build the repository
        uses: ./aws-amplify/.github/actions/node-and-build
  e2e:
    needs: prebuild
    uses: ./.github/workflows/callable-e2e.yml
  bundle-size-tests:
    needs: prebuild
    uses: ./.github/workflows/callable-bundle-size-tests.yml
