on: [push]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          repository: yingku/amplify-js-samples-staging
          path: aws-amplify-staging
          token: ${{ secrets.GH_ACTIONS }} 

  e2e:
    uses: ./.github/workflows/callable-e2e.yml
    secrets: inherit
