name: 'Canary Tests Fix'

on:
  push:
    branches: ['actions-slack-fix']

env:
  WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  slack-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        # env:
        #   WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
        #   WEBHOOK_URL: ${{ env.WEBHOOK_URL }}
        # run: |
        #   curl -X POST -H "Content-Type: application/json" \
        #   --data {URL:$WORKFLOW_URL} \
        #   $WEBHOOK_URL
        env:
          WORKFLOW_URL: '{ "URL": "${{ env.WORKFLOW_URL }}" }'
          WEBHOOK_URL: ${{ env.WEBHOOK_URL }}
        run: |
          export 
          curl -X POST -H "Content-Type: application/json" \
          --data "$WORKFLOW_URL" \
          $WEBHOOK_URL
